#Dont use this file! This project uses pi4j which uses GPIO pins (and computers does'nt have GPIO pins).
#Please use config_pi.yml. Thanks.
logging:
  level: INFO
  loggers:
    greenhouse: DEBUG

tempsensorfile: "/Users/henrikeriksson/w1_slave" #change this to your adafruit tempature sensors "w1_slave" file!
#Format:
#xx xx xx xx xx xx xx xx xx : crc=xx [YES/NO]
#xx xx xx xx xx xx xx xx xx t=xxxxx
#Or:
#xx xx xx xx xx xx xx xx xx : crc=xx [YES/NO]
#xx xx xx xx xx xx xx xx xx t=xxxx

sundial:
  thread-pool-size: 10
  shutdown-on-unload: true
  wait-on-shutdown: false
  start-delay-seconds: 0
  start-scheduler-on-load: true
  global-lock-on-load: false
  annotated-jobs-package-name: se.henrikeriksson.greenhouse.jobs
  tasks: [startjob, stopjob]

mailUser: farsansraspberrypi@gmail.com
mailPassword: ChangeMe