logging:
  level: INFO
  loggers:
    greenhouse: DEBUG

tempsensorfile: "/sys/bus/w1/devices/28-000007105864/w1_slave" #change this to your adafruit tempature sensors "w1_slave" file!

#Format:
#xx xx xx xx xx xx xx xx xx : crc=xx [YES/NO]
#xx xx xx xx xx xx xx xx xx t=xxxxx...

sundial:
  thread-pool-size: 10
  shutdown-on-unload: true
  wait-on-shutdown: false
  start-delay-seconds: 0
  start-scheduler-on-load: true
  global-lock-on-load: false
  annotated-jobs-package-name: se.henrikeriksson.greenhouse.jobs
  tasks: [startjob, stopjob]


mailUser: farsansraspberrypi@gmail.com
mailPassword: ChangeMe